In [2]:
import numpy as np

In [4]:
arr =np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
twod=np.array([[1,2,3],[4,5,6]])
print(twod)

[[1 2 3]
 [4 5 6]]


In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(0,9)    # end one will not be included

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(1,10,2) #(starting,ending,step size) 

array([1, 3, 5, 7, 9])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# ARRAY PROPERTIES


In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


TYPE CONVERSION


In [19]:
arr=np.array([1.2,2.5,3.7])
arr_int=arr.astype(int)
print(arr_int)

[1 2 3]


In [20]:
#indexing
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [ ]:
# 1D slicing
arr=np.array([1,2,3,4,5,6])
print(arr[::6])
print(arr[::-1])
print(arr[::1])
print(arr[1::3])  #here 3 is step size
print(arr[1::2])  #similary 2 is the step size

[1]
[6 5 4 3 2 1]
[1 2 3 4 5 6]
[2 5]
[2 4 6]


In [32]:
# 2D Indexing
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])
print(arr[1])

2
[4 5 6]


In [33]:
# 2d Slicing
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:,1])

[2 5 8]


In [ ]:
    #Copying one array to another
a=np.array([1,2,3])
b=a #this logic is not safe
b[0]=99
print(a)
print(b)


[99  2  3]
[99  2  3]


In [ ]:
    #Copying one array to another
# safe logic as it doesn't changes the original array
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [39]:
    #Arithematic Operations
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [41]:
    # SCALAR OPERATIONS
a=np.array([1,2,3])
print(a+10)
print(a*5)

[11 12 13]
[ 5 10 15]


In [ ]:
    # unfus(UNIVERSAL FUNCTIONS)
arr=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))   # e^x ,2.718
print(np.max(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))  # std is standard deviation

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
7.5
30
5.678908345800274


In [46]:
    #Boolean Indexing
arr=np.array([10,20,30,40,50])
print(arr[arr>25])
print(arr>25)

[30 40 50]
[False False  True  True  True]


In [3]:
   # Broadcasting Rules 
arr=np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [6]:
arr=np.array([[1,2,3],[5,6,7]])
print(arr+5)

[[ 6  7  8]
 [10 11 12]]


In [5]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))
print(A.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


Random Module

In [7]:
np.random.rand(5)

array([0.02013455, 0.49387557, 0.35313168, 0.07912534, 0.32655278])

In [8]:
np.random.rand(3,3)

array([[0.86587628, 0.31423215, 0.57604469],
       [0.41854618, 0.58453055, 0.29790079],
       [0.7207261 , 0.2175027 , 0.56962012]])

In [ ]:
np.random.randint(1,100,15)  #(stating,ending,number of random integers) ,,here ending excluded

array([ 5, 95, 75,  1, 81, 12, 87, 29,  5, 88, 46,  5, 76, 35,  6],
      dtype=int32)

Reshaping Arrays

In [13]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
arr=np.arange(9)
print(arr.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.sum(arr,axis=0))  #Column-wise
print(np.sum(arr,axis=1))  #Row-wise

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


Where in Numpy

In [ ]:
arr=np.array([10,-5,20,-3,15])
result=np.where(arr<0,0,arr)  #here, arr<0 is condition,0 to be printed ifcondition is true,otherwise original arr will be printed 
print(result)

[10  0 20  0 15]


In [ ]:
arr=np.array([10,-5,20,-3,15])
result=np.where(arr%2!=0,-1,arr)
print(result)

[10 -1 20 -1 -1]


In [24]:
marks=np.array([45,78,80,49,73])
status=np.where(marks>=50,1,0)
print(status)

[0 1 1 0 1]


In [25]:
data=np.array([10,20,30,40,50])
mean_val=np.mean(data)
res=np.where(data>mean_val,mean_val,data)
print(res)

[10. 20. 30. 30. 30.]


In [26]:
mat=np.array([[10,60,30],[80,20,90]])
result=np.where(mat>=50,1,0)
print(result)

[[0 1 0]
 [1 0 1]]
