In [4]:
import numpy as np


In [3]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [5,6,7,8],
                 [5,6,7,8],
                 [5,6,7,8]
                 ])
print(arr1.shape)

(5, 4)


In [2]:
import time as t

In [ ]:
start = t.time()
arr1 = np.array[[1,2,3,4],
                 [5,6,7,8],
                 [5,6,7,8],
                 [5,6,7,8],
                 [5,6,7,8]
                 ]
arr1 = np.array([[[[[[[[]]]]]]]])       
print(arr1.shape)

end = t.time()

time = start - end
print(time)



(5, 4)
-0.0009982585906982422
